name: lost-in-the-haystack-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accelerate=1.3.0
  - aiohappyeyeballs=2.4.6
  - aiohttp=3.11.12
  - aiosignal=1.3.2
  - alsa-lib=1.2.13
  - annotated-types=0.7.0
  - anyio=4.8.0
  - aom=3.9.1
  - asttokens=3.0.0
  - attr=2.5.1
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bigquery-magics=0.8.1
  - blinker=1.9.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cachetools=5.5.2
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.11.11
  - cryptography=44.0.2
  - cuda-crt-tools=12.8.61
  - cuda-cudart=12.8.57
  - cuda-cudart_linux-64=12.8.57
  - cuda-cuobjdump=12.8.55
  - cuda-cupti=12.8.57
  - cuda-nvcc-tools=12.8.61
  - cuda-nvdisasm=12.8.55
  - cuda-nvrtc=12.8.61
  - cuda-nvtx=12.8.55
  - cuda-nvvm-tools=12.8.61
  - cuda-version=12.8
  - cudnn=9.7.1.26
  - cusparselt=0.7.0.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - datasets=3.5.0
  - dav1d=1.2.1
  - db-dtypes=1.4.2
  - dbus=1.13.6
  - debugpy=1.8.13
  - decorator=5.2.1
  - deprecated=1.2.18
  - dill=0.3.8
  - distro=1.9.0
  - double-conversion=3.3.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fastavro=1.10.0
  - filelock=3.17.0
  - folium=0.19.5
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.5.0
  - fsspec=2024.9.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.0
  - geotiff=1.7.4
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-api-core=2.24.2
  - google-api-core-grpc=2.24.2
  - google-auth=2.38.0
  - google-auth-oauthlib=1.2.1
  - google-cloud-bigquery=3.30.0
  - google-cloud-bigquery-core=3.30.0
  - google-cloud-bigquery-storage=2.29.1
  - google-cloud-bigquery-storage-core=2.29.1
  - google-cloud-core=2.4.3
  - google-cloud-secret-manager=2.23.2
  - google-crc32c=1.7.1
  - google-genai=1.3.0
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.69.2
  - googleapis-common-protos-grpc=1.69.2
  - graphite2=1.3.13
  - grpc-google-iam-v1=0.14.2
  - grpcio=1.67.1
  - grpcio-status=1.67.1
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.4.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - huggingface_hub=0.28.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.5
  - jiter=0.9.0
  - joblib=1.4.2
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarchive=3.7.7
  - libarrow=19.0.0
  - libarrow-acero=19.0.0
  - libarrow-dataset=19.0.0
  - libarrow-substrait=19.0.0
  - libavif16=1.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcublas=12.8.3.14
  - libcudss0=0.4.0.2
  - libcufft=11.3.3.41
  - libcufile=1.13.0.11
  - libcups=2.3.3
  - libcurand=10.3.9.55
  - libcurl=8.11.1
  - libcusolver=11.7.2.55
  - libcusparse=12.5.7.53
  - libde265=1.0.15
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgdal-core=3.10.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.34.0
  - libgoogle-cloud-storage=2.34.0
  - libgpg-error=1.51
  - libgrpc=1.67.1
  - libheif=1.19.7
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libmagma=2.8.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.8.61
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.4
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.2
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libudev1=257.2
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.8.1
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nccl=2.25.1.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - nomkl=1.0
  - numpy=2.2.3
  - oauthlib=3.2.2
  - openai=1.66.3
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.5.0
  - opentelemetry-api=1.31.1
  - opentelemetry-instrumentation=0.52b1
  - opentelemetry-sdk=1.31.1
  - opentelemetry-semantic-conventions=0.52b1
  - orc=2.0.3
  - packaging=24.2
  - pandas=2.2.3
  - pandas-gbq=0.27.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - platformdirs=4.3.7
  - proj=9.5.1
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.50
  - propcache=0.2.1
  - proto-plus=1.26.1
  - protobuf=5.28.3
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pyarrow-core=19.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pydata-google-auth=1.9.0
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyogrio=0.10.0
  - pyopenssl=25.0.0
  - pyparsing=3.2.1
  - pyproj=3.7.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-tzdata=2025.1
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qt6-main=6.8.2
  - rav1e=0.6.6
  - rdma-core=56.0
  - re2=2024.07.02
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.9
  - s2n=1.5.11
  - safetensors=0.5.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - shapely=2.0.7
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - sqlite=3.48.0
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - svt-av1=3.0.2
  - threadpoolctl=3.6.0
  - tiktoken=0.9.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.48.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - unicodedata2=16.0.0
  - uriparser=0.9.8
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - websockets=14.2
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.2
  - xyzservices=2025.1.0
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - antlr4-python3-runtime==4.13.2
      - azure-ai-inference==1.0.0b9
      - azure-core==1.34.0
      - beautifulsoup4==4.13.4
      - cbor==1.0.0
      - ijson==3.3.0
      - inscriptis==2.6.0
      - ir-datasets==0.5.10
      - isodate==0.7.2
      - latex2sympy2-extended==1.10.1
      - lxml==5.3.2
      - lz4==4.4.4
      - math-verify==0.7.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - soupsieve==2.7
      - sympy==1.13.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - trec-car-tools==2.6
      - triton==3.2.0
      - unlzw3==0.2.3
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - zlib-state==0.1.9